import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./_mainComponents/Sidebar";
import Header from "./_mainComponents/Header";
import { Suspense } from "react";
import LoadingSpinner from "./_mainComponents/LoadingSpinner";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Providers from "./_utils/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-900`}
      >
        <ToastContainer
          position="top-center"
          autoClose={2000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
        <Providers>
          {" "}
          {/* Wrap everything inside the Providers component */}
          <div className="min-h-screen flex flex-col">
            <Header />
            <div className="flex flex-1">
              <Sidebar />
              <Suspense fallback={<LoadingSpinner />}>
                <main className="flex-1 bg-gradient-to-br from-slate-900 to-slate-800 ml-48 pt-20">
                  {children}
                </main>
              </Suspense>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
